# Generated by Django 4.2 on 2023-05-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_incidents_priority_alter_incidents_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
