# Generated by Django 4.2 on 2023-05-01 06:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_incidents_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incid_id',
            field=models.CharField(default=core.models.gen_incid_id, max_length=9999, unique=True),
        ),
    ]
