# Generated by Django 4.2 on 2023-05-01 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_incidents_incid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
