# Generated by Django 4.2 on 2023-05-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_incidents_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incid_id',
            field=models.CharField(blank=True, max_length=9999, null=True, unique=True),
        ),
    ]
