# Generated by Django 4.2 on 2023-05-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_incidents_incid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidents',
            name='incid_id',
        ),
        migrations.AlterField(
            model_name='incidents',
            name='id',
            field=models.CharField(max_length=9999, primary_key=True, serialize=False, unique=True),
        ),
    ]
