# Generated by Django 4.2 on 2023-05-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_incidents_incid_id_alter_incidents_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('closed', 'Closed')], max_length=9999),
        ),
    ]
