# Generated by Django 4.2 on 2023-05-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_incidents_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('closed', 'Closed')], default='open', max_length=9999),
        ),
    ]
